//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("是")]
        public string button1 {
            get {
                return ((string)(this["button1"]));
            }
            set {
                this["button1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("用户名")]
        public string label1 {
            get {
                return ((string)(this["label1"]));
            }
            set {
                this["label1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("密码")]
        public string label {
            get {
                return ((string)(this["label"]));
            }
            set {
                this["label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("注册")]
        public string button2 {
            get {
                return ((string)(this["button2"]));
            }
            set {
                this["button2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("登录")]
        public string button3 {
            get {
                return ((string)(this["button3"]));
            }
            set {
                this["button3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("checkBox1")]
        public string 管理员登录 {
            get {
                return ((string)(this["管理员登录"]));
            }
            set {
                this["管理员登录"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("管理员登录")]
        public string checkBox1 {
            get {
                return ((string)(this["checkBox1"]));
            }
            set {
                this["checkBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("button1")]
        public string 查看信息 {
            get {
                return ((string)(this["查看信息"]));
            }
            set {
                this["查看信息"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("查看信息")]
        public string userbutton1 {
            get {
                return ((string)(this["userbutton1"]));
            }
            set {
                this["userbutton1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("修改信息")]
        public string userbotton2 {
            get {
                return ((string)(this["userbotton2"]));
            }
            set {
                this["userbotton2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("用户id")]
        public string idlabel {
            get {
                return ((string)(this["idlabel"]));
            }
            set {
                this["idlabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("姓名")]
        public string namelabel {
            get {
                return ((string)(this["namelabel"]));
            }
            set {
                this["namelabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("用户id：")]
        public string idlb {
            get {
                return ((string)(this["idlb"]));
            }
            set {
                this["idlb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("姓名：")]
        public string namelb {
            get {
                return ((string)(this["namelb"]));
            }
            set {
                this["namelb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("身份证号：")]
        public string idcodelb {
            get {
                return ((string)(this["idcodelb"]));
            }
            set {
                this["idcodelb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("性别")]
        public string sexlb {
            get {
                return ((string)(this["sexlb"]));
            }
            set {
                this["sexlb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("性别：")]
        public string sex1lb {
            get {
                return ((string)(this["sex1lb"]));
            }
            set {
                this["sex1lb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("年龄：")]
        public string agelb {
            get {
                return ((string)(this["agelb"]));
            }
            set {
                this["agelb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("完成")]
        public string userbutton3 {
            get {
                return ((string)(this["userbutton3"]));
            }
            set {
                this["userbutton3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("清空")]
        public string userclear {
            get {
                return ((string)(this["userclear"]));
            }
            set {
                this["userclear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("添加线路")]
        public string adminbt {
            get {
                return ((string)(this["adminbt"]));
            }
            set {
                this["adminbt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("线路id：")]
        public string label11 {
            get {
                return ((string)(this["label11"]));
            }
            set {
                this["label11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("起点")]
        public string label12 {
            get {
                return ((string)(this["label12"]));
            }
            set {
                this["label12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("起点：")]
        public string alvel2 {
            get {
                return ((string)(this["alvel2"]));
            }
            set {
                this["alvel2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("终点：")]
        public string label13 {
            get {
                return ((string)(this["label13"]));
            }
            set {
                this["label13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("发车时间")]
        public string label14 {
            get {
                return ((string)(this["label14"]));
            }
            set {
                this["label14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("到达时间")]
        public string label15 {
            get {
                return ((string)(this["label15"]));
            }
            set {
                this["label15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("车牌号：")]
        public string label17 {
            get {
                return ((string)(this["label17"]));
            }
            set {
                this["label17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("到达时间：")]
        public string la11 {
            get {
                return ((string)(this["la11"]));
            }
            set {
                this["la11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("发车时间：")]
        public string lb11 {
            get {
                return ((string)(this["lb11"]));
            }
            set {
                this["lb11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("座位数：")]
        public string lb12 {
            get {
                return ((string)(this["lb12"]));
            }
            set {
                this["lb12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("价格：")]
        public string lb13 {
            get {
                return ((string)(this["lb13"]));
            }
            set {
                this["lb13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("添加")]
        public string lb15 {
            get {
                return ((string)(this["lb15"]));
            }
            set {
                this["lb15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("查询线路")]
        public string l15 {
            get {
                return ((string)(this["l15"]));
            }
            set {
                this["l15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("要查询的目的地")]
        public string lb17 {
            get {
                return ((string)(this["lb17"]));
            }
            set {
                this["lb17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("查询")]
        public string lb18 {
            get {
                return ((string)(this["lb18"]));
            }
            set {
                this["lb18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("要查询的目的地：")]
        public string lb19 {
            get {
                return ((string)(this["lb19"]));
            }
            set {
                this["lb19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("查看全部")]
        public string lb20 {
            get {
                return ((string)(this["lb20"]));
            }
            set {
                this["lb20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("更新线路")]
        public string lb21 {
            get {
                return ((string)(this["lb21"]));
            }
            set {
                this["lb21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("更新")]
        public string lb22 {
            get {
                return ((string)(this["lb22"]));
            }
            set {
                this["lb22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("查找")]
        public string lb23 {
            get {
                return ((string)(this["lb23"]));
            }
            set {
                this["lb23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("清空")]
        public string lb24 {
            get {
                return ((string)(this["lb24"]));
            }
            set {
                this["lb24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("添加车辆")]
        public string lb26 {
            get {
                return ((string)(this["lb26"]));
            }
            set {
                this["lb26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("全部订单")]
        public string lb27 {
            get {
                return ((string)(this["lb27"]));
            }
            set {
                this["lb27"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("更改密码")]
        public string lb28 {
            get {
                return ((string)(this["lb28"]));
            }
            set {
                this["lb28"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("删除")]
        public string lb29 {
            get {
                return ((string)(this["lb29"]));
            }
            set {
                this["lb29"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("车牌号：")]
        public string lb30 {
            get {
                return ((string)(this["lb30"]));
            }
            set {
                this["lb30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("司机：")]
        public string lb31 {
            get {
                return ((string)(this["lb31"]));
            }
            set {
                this["lb31"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("座位数：")]
        public string lb32 {
            get {
                return ((string)(this["lb32"]));
            }
            set {
                this["lb32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("车辆类型：")]
        public string lb33 {
            get {
                return ((string)(this["lb33"]));
            }
            set {
                this["lb33"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("添加")]
        public string lb34 {
            get {
                return ((string)(this["lb34"]));
            }
            set {
                this["lb34"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("修改")]
        public string lb35 {
            get {
                return ((string)(this["lb35"]));
            }
            set {
                this["lb35"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("清空")]
        public string lb36 {
            get {
                return ((string)(this["lb36"]));
            }
            set {
                this["lb36"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Id")]
        public string lb40 {
            get {
                return ((string)(this["lb40"]));
            }
            set {
                this["lb40"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("要修改的Id:")]
        public string lb41 {
            get {
                return ((string)(this["lb41"]));
            }
            set {
                this["lb41"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("输入原密码：")]
        public string lb42 {
            get {
                return ((string)(this["lb42"]));
            }
            set {
                this["lb42"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("输入新密码：")]
        public string lb43 {
            get {
                return ((string)(this["lb43"]));
            }
            set {
                this["lb43"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("确定")]
        public string lb44 {
            get {
                return ((string)(this["lb44"]));
            }
            set {
                this["lb44"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("查询线路")]
        public string lb45 {
            get {
                return ((string)(this["lb45"]));
            }
            set {
                this["lb45"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("修改密码")]
        public string lb46 {
            get {
                return ((string)(this["lb46"]));
            }
            set {
                this["lb46"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("购票")]
        public string lb48 {
            get {
                return ((string)(this["lb48"]));
            }
            set {
                this["lb48"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("查看")]
        public string lb49 {
            get {
                return ((string)(this["lb49"]));
            }
            set {
                this["lb49"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("购买")]
        public string lb50 {
            get {
                return ((string)(this["lb50"]));
            }
            set {
                this["lb50"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("输入要购买的线路ID：")]
        public string lb51 {
            get {
                return ((string)(this["lb51"]));
            }
            set {
                this["lb51"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("线路ID:")]
        public string lb52 {
            get {
                return ((string)(this["lb52"]));
            }
            set {
                this["lb52"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("起点：")]
        public string lb53 {
            get {
                return ((string)(this["lb53"]));
            }
            set {
                this["lb53"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("终点：")]
        public string lb54 {
            get {
                return ((string)(this["lb54"]));
            }
            set {
                this["lb54"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("发车时间：")]
        public string lb55 {
            get {
                return ((string)(this["lb55"]));
            }
            set {
                this["lb55"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("到达时间：")]
        public string lb56 {
            get {
                return ((string)(this["lb56"]));
            }
            set {
                this["lb56"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("车牌号：")]
        public string lb57 {
            get {
                return ((string)(this["lb57"]));
            }
            set {
                this["lb57"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("剩余座位：")]
        public string lb58 {
            get {
                return ((string)(this["lb58"]));
            }
            set {
                this["lb58"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("价格：")]
        public string lb59 {
            get {
                return ((string)(this["lb59"]));
            }
            set {
                this["lb59"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("查看订单")]
        public string lb60 {
            get {
                return ((string)(this["lb60"]));
            }
            set {
                this["lb60"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("查看")]
        public string lb61 {
            get {
                return ((string)(this["lb61"]));
            }
            set {
                this["lb61"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("删除")]
        public string lb62 {
            get {
                return ((string)(this["lb62"]));
            }
            set {
                this["lb62"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("车辆管理")]
        public string lb63 {
            get {
                return ((string)(this["lb63"]));
            }
            set {
                this["lb63"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("目的地：")]
        public string lb64 {
            get {
                return ((string)(this["lb64"]));
            }
            set {
                this["lb64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("时间")]
        public string lb65 {
            get {
                return ((string)(this["lb65"]));
            }
            set {
                this["lb65"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("时间：")]
        public string lb66 {
            get {
                return ((string)(this["lb66"]));
            }
            set {
                this["lb66"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("中间站点：")]
        public string lb67 {
            get {
                return ((string)(this["lb67"]));
            }
            set {
                this["lb67"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("本人购买")]
        public string lb68 {
            get {
                return ((string)(this["lb68"]));
            }
            set {
                this["lb68"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("输入要代买人的信息：")]
        public string lb69 {
            get {
                return ((string)(this["lb69"]));
            }
            set {
                this["lb69"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("姓名：")]
        public string lb70 {
            get {
                return ((string)(this["lb70"]));
            }
            set {
                this["lb70"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("证件号：")]
        public string lb71 {
            get {
                return ((string)(this["lb71"]));
            }
            set {
                this["lb71"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("代买")]
        public string lb72 {
            get {
                return ((string)(this["lb72"]));
            }
            set {
                this["lb72"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("中间站：")]
        public string lb73 {
            get {
                return ((string)(this["lb73"]));
            }
            set {
                this["lb73"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("线路管理")]
        public string lb74 {
            get {
                return ((string)(this["lb74"]));
            }
            set {
                this["lb74"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("出发地：")]
        public string lb75 {
            get {
                return ((string)(this["lb75"]));
            }
            set {
                this["lb75"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("中间站1：")]
        public string lb76 {
            get {
                return ((string)(this["lb76"]));
            }
            set {
                this["lb76"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("中间站2：")]
        public string lb77 {
            get {
                return ((string)(this["lb77"]));
            }
            set {
                this["lb77"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("中间站3：")]
        public string lb78 {
            get {
                return ((string)(this["lb78"]));
            }
            set {
                this["lb78"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("终点：")]
        public string lb79 {
            get {
                return ((string)(this["lb79"]));
            }
            set {
                this["lb79"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("添加")]
        public string lb80 {
            get {
                return ((string)(this["lb80"]));
            }
            set {
                this["lb80"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("查看")]
        public string lb81 {
            get {
                return ((string)(this["lb81"]));
            }
            set {
                this["lb81"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("修改")]
        public string lb82 {
            get {
                return ((string)(this["lb82"]));
            }
            set {
                this["lb82"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("删除")]
        public string lb83 {
            get {
                return ((string)(this["lb83"]));
            }
            set {
                this["lb83"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("button5")]
        public string lb84 {
            get {
                return ((string)(this["lb84"]));
            }
            set {
                this["lb84"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("清空")]
        public string lb85 {
            get {
                return ((string)(this["lb85"]));
            }
            set {
                this["lb85"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("线路编号：")]
        public string lb86 {
            get {
                return ((string)(this["lb86"]));
            }
            set {
                this["lb86"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("取消订单")]
        public string lb87 {
            get {
                return ((string)(this["lb87"]));
            }
            set {
                this["lb87"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("查看")]
        public string lb89 {
            get {
                return ((string)(this["lb89"]));
            }
            set {
                this["lb89"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("购票ID：")]
        public string lb88 {
            get {
                return ((string)(this["lb88"]));
            }
            set {
                this["lb88"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("出发地：")]
        public string lb90 {
            get {
                return ((string)(this["lb90"]));
            }
            set {
                this["lb90"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("目的地：")]
        public string lb91 {
            get {
                return ((string)(this["lb91"]));
            }
            set {
                this["lb91"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("查询")]
        public string lb92 {
            get {
                return ((string)(this["lb92"]));
            }
            set {
                this["lb92"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("本人购买")]
        public string lb93 {
            get {
                return ((string)(this["lb93"]));
            }
            set {
                this["lb93"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("label4")]
        public string lb94 {
            get {
                return ((string)(this["lb94"]));
            }
            set {
                this["lb94"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("身份证号：")]
        public string lb95 {
            get {
                return ((string)(this["lb95"]));
            }
            set {
                this["lb95"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("姓名：")]
        public string lb96 {
            get {
                return ((string)(this["lb96"]));
            }
            set {
                this["lb96"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("购买")]
        public string lb97 {
            get {
                return ((string)(this["lb97"]));
            }
            set {
                this["lb97"] = value;
            }
        }
    }
}
